/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.UIManager;

/**
 *
 * @author benmo
 */
public class ORRDNSM extends javax.swing.JFrame {
    

    /**
     * Creates new form ORRDNSM
     */
    public ORRDNSM() {
    initComponents();
    this.setResizable(false);
     this.setLocationRelativeTo(null);
    }
    ArrayList<Double>M ;
    ArrayList<Double> A ;
    ArrayList<Double> B ;
    ArrayList<Double> C ;
    ArrayList<Double> AA ;
    ArrayList<Double> BB ;
    ArrayList<Double> CC ;
    ArrayList<Double> temp1 ;
    ArrayList<String> paquet ;
    ArrayList<Double> f1 ;
    ArrayList<Double> f2 ;
    ArrayList<Double> f3 ;
    Double dca ;
    Double dcb ;
    Double dcc ;
    static int a , b , c ;
          String s ;
          Double test ;boolean t ;
    
    public void maj(){ 
                      boolean g=false;
                      if(!f1.isEmpty()) f1.clear();
                      if(!f2.isEmpty())  f2.clear();
                      if(!f3.isEmpty())  f3.clear();
                      if(a!=A.size()) {
                                       for (int i = a; i < A.size(); i++) {
                                       if(A.get(i)<test || A.get(i).equals(test)){f1.add(AA.get(i));g=true;}else{break;}
                                       }
                      }
                      
                      if(b!=B.size()) {
                                       for (int i = b; i < B.size(); i++) {
                                       if(B.get(i)<test || B.get(i).equals(test)){f2.add(BB.get(i));g=true;}else{break;}
                                       }
                      }
             
                      if(c!=C.size()) {
                                       for (int i = c; i < C.size(); i++) {
                                       if(C.get(i)<test || C.get(i).equals(test)){f3.add(CC.get(i));g=true;}else{break;}
                                       } 
                      }
             
             if(!g){if(!A.isEmpty() && a!=A.size()){M.add(A.get(a));}
             if(!B.isEmpty() && b!=B.size()){M.add(B.get(b));}
             if(!C.isEmpty() && c!=C.size()){M.add(C.get(c));}
             if(!M.isEmpty()) {dca=0.0;dcb=0.0;dcc=0.0; test=Collections.min(M);M.clear();maj();}   
             }
              
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTExtField1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "0.5", "1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("DWRR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("M1(A)");

        jLabel2.setText("M2(B)");

        jLabel3.setText("M3(C)");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("DC");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SPQ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("RR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        JTExtField1.setColumns(20);
        JTExtField1.setRows(5);
        JTExtField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTExtField1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTExtField1);

        jLabel4.setText("Resultat:");

        jButton4.setText("Retour");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(99, 99, 99))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        a=0;b=0;c=0;
        dca =0.0;dcb =0.0;dcc =0.0;
        s="";
        M = new ArrayList<Double>();
        A = new ArrayList<Double>();
        B = new ArrayList<Double>();
        C = new ArrayList<Double>();
        AA = new ArrayList<Double>();
        BB = new ArrayList<Double>();
        CC = new ArrayList<Double>();
        f1 = new ArrayList<Double>();
        f2 = new ArrayList<Double>();
        f3 = new ArrayList<Double>();
        temp1 = new ArrayList<Double>();
        paquet = new ArrayList<String>();
        Double wa ;
        Double wb ;
        Double wc ;
        if(jRadioButton1.isSelected()){
            wa=Double.parseDouble(jTextField1.getText());
            wb=Double.parseDouble(jTextField2.getText());
            wc=Double.parseDouble(jTextField3.getText());
        }else{wa=500.0;wb=500.0;wc=500.0;}

        try {

            for (int j = 0; j < jTable1.getColumnCount(); j++) {

                if((Double) jTable1.getModel().getValueAt(0, j)!=null) { AA.add((Double) jTable1.getModel().getValueAt(0, j));A.add(Double.parseDouble(jTable1.getColumnName(j)));}
                if((Double) jTable1.getModel().getValueAt(1, j)!=null) { BB.add((Double) jTable1.getModel().getValueAt(1, j));B.add(Double.parseDouble(jTable1.getColumnName(j)));}
                if((Double) jTable1.getModel().getValueAt(2, j)!=null) { CC.add((Double) jTable1.getModel().getValueAt(2, j));C.add(Double.parseDouble(jTable1.getColumnName(j)));}
            }
        } catch (Exception e) {
            System.err.println("erreur de copier les valeur");
        }

        if(!A.isEmpty()){M.add(A.get(0));}
        if(!B.isEmpty()){M.add(B.get(0));}
        if(!C.isEmpty()){M.add(C.get(0));}
        if(!M.isEmpty()) {  test=Collections.min(M);}else {test=0.0;}
        if(!M.isEmpty())  M.clear();

        maj();
        t=true;
        while (a!=A.size() || b!=B.size() || c!=C.size()) {

            dca=dca+wa;
            if(f1.isEmpty()){dca=0.0;}
            while(t){
                if(f1.isEmpty()){break;}

                if(f1.get(0)<dca || f1.get(0).equals(dca)){dca=dca-f1.get(0);temp1.add(test+f1.get(0)/1000);test=test+f1.get(0)/1000;paquet.add("A");s=s+"A";a++;maj();}else{break;}
            }
            dcb=dcb+wb;
            if(f2.isEmpty()){dcb=0.0;}
            while(t){
                if(f2.isEmpty()){break;}

                if(f2.get(0)<dcb || f2.get(0).equals(dcb)){dcb=dcb-f2.get(0);temp1.add(test+f2.get(0)/1000);test=test+f2.get(0)/1000;paquet.add("B");s=s+"B";b++;maj();}else{break;}
            }
            dcc=dcc+wc;
            if(f3.isEmpty()){dcc=0.0;}
            while(t){
                if(f3.isEmpty()){break;}

                if(f3.get(0)<dcc || f3.get(0).equals(dcc)){dcc=dcc-f3.get(0);temp1.add(test+f3.get(0)/1000);test=test+f3.get(0)/1000;paquet.add("C");s=s+"C";c++;maj();}else{break;}
            }

        }
        jLabel4.setText("L'ordennancement de DWRR :");
        JTExtField1.setText(s+" temp = "+test+"\n-------------------\n");
        
     
        for (int i = 0; i < temp1.size(); i++) {
            JTExtField1.setText("\n"+JTExtField1.getText()+temp1.get(i)+" --- "+paquet.get(i)+"\n");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int l = 0;
        int m = 0;
        int n = 0;
        int i = 0;
        String sortie2 = "";
        Object mat[][] = new Object[3][20];
        try {
            for (int ii = 0; ii < 3; ii++) {
                for (int j = 0; j < 20; j++) {
                    mat[ii][j] = jTable1.getValueAt(ii, j);
                }
            }
        } catch (Exception e) {
            System.err.println("erreur de copier les valeur");
        }
        double t = 0.5;
        String sortie = "";
        for (i = 0; i < 60; i++) {
            if (i < 20) {
                if (mat[0][i] != null) {
                    l++;
                }
                if (mat[1][i] != null) {
                    m++;
                }
                if (mat[2][i] != null) {
                    n++;
                }
            }
           
            
            t += 0.5;
            if (l > 0) {

                l--;
                sortie += "(A  ;" + t + ")" + "-->";
            } else if (m > 0) {
                m--;
                sortie += "(B  ;" + t + ")" + "-->";
            } else if (n > 0) {
                n--;
                sortie += "(C  ;" + t + ")" + "-->";
            } else {
                sortie += " ";
            }

        }
        jLabel4.setText("L'ordennancement de SPQ :");
        JTExtField1.setText(sortie);

                                        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           int l = 0;
        int m = 0;
        int n = 0;
        int i = 0;
        int v =0;
        boolean a=true,b=true,c=true;
        String[] mat1 = new String[21];
        String[] mat2 = new String[21];
        String[] mat3 = new String[21];
   
        
           
  Object mat[][] = new Object[3][20];
        try {
            for (int ii = 0; ii < 3; ii++) {
                for (int j = 0; j < 20; j++) {
                    mat[ii][j] = jTable1.getValueAt(ii, j);
                }
            } } catch (Exception e) {
            System.err.println("erreur de copier les valeur");
        }
        
        double t = 0.5;
        String sortie = "";
        for (i = 0; i < 60; i++) {
            if (i < 20) {
                if (mat[0][i] != null) {
                    l++;
                }
                if (mat[1][i] != null) {
                    m++;
                }
                if (mat[2][i] != null) {
                    n++;
                }
            }
             
               
          
            if (l > 0 && a==true) {
                a=false;
                b=true;
                t += 0.5;

                l--;
                v++;
                sortie += "(A  ;" + t + ")" + "-->";
                
            } else{if(l==0)c=true;
           if (m > 0 && b==true) {
                b=false;
                c=true;
                t += 0.5;
                m--;
                v++;
                
                sortie += "(B  ;" + t + ")" + "-->";
                
            } else{if(m==0)b=true;
            if (n > 0&& c==true) {
                c=false;
                a=true;
                t += 0.5;
                n--;
                v++;
                sortie += "(C  ;" + t + ")" + "-->";
                
            } else {if(n==0)a=true;
                sortie += " ";
            
            }} if (v == 0 ) {
                
                t += 0.5;
               
            }
             v=0;
            }
            
            
            
        }
                jLabel4.setText("L'ordennancement de RR :");

        JTExtField1.setText(sortie);
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    choisir choix = new choisir();
        choix.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JTExtField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTExtField1MouseClicked
      JTExtField1.setEditable(false);
    }//GEN-LAST:event_JTExtField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {

            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ORRDNSM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTExtField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
